#!/usr/bin/env python
from pathlib import Path
import os.path

SCRIPT_DIRECTORY = Path(__file__).parent

print("#" * 80)
print(f"# This file was autogenerated by `{Path(__file__).name}'")
print(f"# DO NOT MODIFY THIS FILE DIRECTLY")
print(f"# Instead modify `{Path(__file__).name}' and re-run `make'")
print("#" * 80)
print("")
print("SKIP_FILES?=")
print("")
print("SKIP_IF_NOT_NEW?=")
print("")
endifs = []
MIN_VER = 8
MAX_VER = 19
for ver in reversed(range(MIN_VER, MAX_VER + 1)):
    fname = f"skip-8.{ver}-older.txt"
    if not os.path.exists(SCRIPT_DIRECTORY / fname):
        with open(SCRIPT_DIRECTORY / fname, "a") as f:
            pass
    print(f"ifneq (,$(filter 8.{ver}%,$(COQ_VERSION)))")
    print(f"SKIP_FILES+=skip-8.{ver}-older.txt $(SKIP_IF_NOT_NEW)")
    print("else")
    if ver == MIN_VER:
        print("# new version, don't skip")
    else:
        print(f"SKIP_IF_NOT_NEW+=skip-8.{ver}-older.txt")
    endifs.append("endif")
print("\n".join(endifs))
