################################################################################
# This file was autogenerated by `generate-skip.py'
# DO NOT MODIFY THIS FILE DIRECTLY
# Instead modify `generate-skip.py' and re-run `make'
################################################################################

SKIP_FILES?=

SKIP_IF_NOT_NEW?=

ifneq (,$(filter 8.19%,$(COQ_VERSION)))
SKIP_FILES+=skip-8.19-older.txt $(SKIP_IF_NOT_NEW)
else
SKIP_IF_NOT_NEW+=skip-8.19-older.txt
ifneq (,$(filter 8.18%,$(COQ_VERSION)))
SKIP_FILES+=skip-8.18-older.txt $(SKIP_IF_NOT_NEW)
else
SKIP_IF_NOT_NEW+=skip-8.18-older.txt
ifneq (,$(filter 8.17%,$(COQ_VERSION)))
SKIP_FILES+=skip-8.17-older.txt $(SKIP_IF_NOT_NEW)
else
SKIP_IF_NOT_NEW+=skip-8.17-older.txt
ifneq (,$(filter 8.16%,$(COQ_VERSION)))
SKIP_FILES+=skip-8.16-older.txt $(SKIP_IF_NOT_NEW)
else
SKIP_IF_NOT_NEW+=skip-8.16-older.txt
ifneq (,$(filter 8.15%,$(COQ_VERSION)))
SKIP_FILES+=skip-8.15-older.txt $(SKIP_IF_NOT_NEW)
else
SKIP_IF_NOT_NEW+=skip-8.15-older.txt
ifneq (,$(filter 8.14%,$(COQ_VERSION)))
SKIP_FILES+=skip-8.14-older.txt $(SKIP_IF_NOT_NEW)
else
SKIP_IF_NOT_NEW+=skip-8.14-older.txt
ifneq (,$(filter 8.13%,$(COQ_VERSION)))
SKIP_FILES+=skip-8.13-older.txt $(SKIP_IF_NOT_NEW)
else
SKIP_IF_NOT_NEW+=skip-8.13-older.txt
ifneq (,$(filter 8.12%,$(COQ_VERSION)))
SKIP_FILES+=skip-8.12-older.txt $(SKIP_IF_NOT_NEW)
else
SKIP_IF_NOT_NEW+=skip-8.12-older.txt
ifneq (,$(filter 8.11%,$(COQ_VERSION)))
SKIP_FILES+=skip-8.11-older.txt $(SKIP_IF_NOT_NEW)
else
SKIP_IF_NOT_NEW+=skip-8.11-older.txt
ifneq (,$(filter 8.10%,$(COQ_VERSION)))
SKIP_FILES+=skip-8.10-older.txt $(SKIP_IF_NOT_NEW)
else
SKIP_IF_NOT_NEW+=skip-8.10-older.txt
ifneq (,$(filter 8.9%,$(COQ_VERSION)))
SKIP_FILES+=skip-8.9-older.txt $(SKIP_IF_NOT_NEW)
else
SKIP_IF_NOT_NEW+=skip-8.9-older.txt
ifneq (,$(filter 8.8%,$(COQ_VERSION)))
SKIP_FILES+=skip-8.8-older.txt $(SKIP_IF_NOT_NEW)
else
# new version, don't skip
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
